### ISSUE TITLE
No gzip support && open closed

### ISSUE THREAD

**Issue by getorca** [umarbutler/orjsonl#1]
To me it would be essential to support compression.

As well, I believe, https://github.com/umarbutler/orjsonl/blob/4de8ff73f050d81fd455eadd3e3f8559015c609e/src/orjsonl/orjsonl.py#L18, could lead to a memory leak when the open file isn't closed.

**Comment by umarbutler** [comment]
> To me it would be essential to support compression.

I've just updated the library to support gzip, bzip2, xz and Zstandard compression.

> , could lead to a memory leak when the open file isn't closed.

Good pickup. The file didn't appear to close even when the map object had been exhuasted. I've fixed that by changing `stream()` into a `generator` function and enclosing `for json in line: yield orjson.loads(json)` in a `with` statement.
