### ISSUE TITLE
Add to conda-forge

### ISSUE THREAD

**Issue by corneliusroemer** [umarbutler/orjsonl#2]
Would be great if this package was available via conda-forge: https://github.com/conda-forge/staged-recipes/issues/26891

**Comment by corneliusroemer** [comment]
https://github.com/conda-forge/staged-recipes/pull/26904

**Comment by corneliusroemer** [comment]
Now available in conda-forge: https://github.com/conda-forge/orjsonl-feedstock
https://anaconda.org/conda-forge/orjsonl

**Comment by umarbutler** [comment]
@corneliusroemer Thanks for this! I was going get on this today but glad to hear you got it done. I don't use conda, however, I may look into making my other libraries available on it if others will find it useful :)

**Comment by corneliusroemer** [comment]
@umarbutler this was never meant to be a todo for you - just an expression of interest in case someone else gets to it before me.

We're using conda a lot in my sphere of bioinformatics because it's probably the best cross-platform package manager there is, going well beyond Python: many bioinfo tools (and also general utilities) have been packaged so one can spin up an environment on all sorts of architectures and oses, across the whole product of `{linux, macos} x {x86_64, arm/aarch}`

It's very easy to add pure Python packages with grayskull, compiled things can be a bit more tricky but it's not too bad.

While it's possible to install pip-only (i.e. not conda-packaged) packages in conda environments, the conda solver won't know about them so it's best to only do this temporarily - hence my packaging up orjsonl

**Comment by umarbutler** [comment]
@corneliusroemer Thanks for the crash course! I didn't know `conda` could be used for more than just Python, that's bring a lot of things into perspective, I wondered why not just use `venv` and/or `pyenv`.

Having a look at the instructions now, they seem a bit involved 😅 (at least relative to `pip` which is just `py -m build; py -m twine upload --repository pypi dist/*`). Do you know an easier way than [this](https://conda-forge.org/docs/maintainer/adding_pkgs/#the-staging-process)?
